CREATE DATABASE SECURITYDB;
USE SECURITYDB;

CREATE TABLE USERS(
  USERNAME VARCHAR(50) NOT NULL,
  PASSWORD VARCHAR(120) NOT NULL,
  ENABLE TINYINT(1) NOT NULL,
  PRIMARY KEY(USERNAME)
);

CREATE TABLE AUTHORITES(
	USERNAME VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    CONSTRAINT AUTHORITIES_IBFK_1
    FOREIGN KEY (USERNAME)
    REFERENCES USERS (USERNAME)
);

ALTER TABLE AUTHORITES RENAME TO AUTHORITIES;
DESC USERS;
DESC AUTHORITIES;

INSERT INTO USERS VALUES('ADMIN','$2a$12$pIdmVtxawfpUxd0oxyeXk.Jv2OP7O0PqYr3D4lnJ1aXBsOREkD32O',1);
INSERT INTO USERS VALUES('USER','$2a$12$y85pkMgtaXf8rzGo.PBXT.Vrys8J0Nxp8TuqZ9xG.jekhJ8gRaOF.',1);

INSERT INTO AUTHORITIES VALUES ('ADMIN','ROLE_ADMIN');
INSERT INTO AUTHORITIES VALUES ('ADMIN','ROLE_USER');
INSERT INTO AUTHORITIES VALUES ('USER','ROLE_USER');

ALTER TABLE USERS CHANGE COLUMN ENABLE ENABLED TINYINT(1); 
select * from authorities;